export const tippyMakerAbi = [
  {
    type: 'function',
    name: 'createCampaign',
    stateMutability: 'payable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'mode', type: 'uint8' },
      { name: 'metadataURI', type: 'string' },
      { name: 'submissionsClose', type: 'uint64' },
      { name: 'claimDeadline', type: 'uint64' },
      { name: 'seedAmount', type: 'uint256' },
    ],
    outputs: [{ name: 'id', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'fund',
    stateMutability: 'payable',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'tip',
    stateMutability: 'payable',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'amount', type: 'uint256' },
      { name: 'note', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleWinners',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'winners', type: 'address[]' },
      { name: 'amounts', type: 'uint256[]' },
      { name: 'submissionHashes', type: 'bytes32[]' },
      { name: 'verdictHash', type: 'bytes32' },
      { name: 'payoutNote', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claim',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'reclaimUnclaimed',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'winners', type: 'address[]' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'payTip',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'submissionHash', type: 'bytes32' },
      { name: 'verdictHash', type: 'bytes32' },
      { name: 'payoutNote', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'finalize',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'updateMetadata',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'metadataURI', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'campaignsCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getCampaign',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'organizer', type: 'address' },
          { name: 'token', type: 'address' },
          { name: 'mode', type: 'uint8' },
          { name: 'metadataURI', type: 'string' },
          { name: 'prizePool', type: 'uint256' },
          { name: 'totalFunded', type: 'uint256' },
          { name: 'totalTipped', type: 'uint256' },
          { name: 'totalPaidOut', type: 'uint256' },
          { name: 'totalEntitled', type: 'uint256' },
          { name: 'submissionsClose', type: 'uint64' },
          { name: 'claimDeadline', type: 'uint64' },
          { name: 'createdAt', type: 'uint64' },
          { name: 'finalized', type: 'bool' },
          { name: 'latestVerdictHash', type: 'bytes32' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'entitlementOf',
    stateMutability: 'view',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'winner', type: 'address' },
    ],
    outputs: [
      { name: 'amount', type: 'uint256' },
      { name: 'claimed', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'submissionPaid',
    stateMutability: 'view',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'submissionHash', type: 'bytes32' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'getRecentCampaigns',
    stateMutability: 'view',
    inputs: [
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      {
        name: 'page',
        type: 'tuple[]',
        components: [
          { name: 'organizer', type: 'address' },
          { name: 'token', type: 'address' },
          { name: 'mode', type: 'uint8' },
          { name: 'metadataURI', type: 'string' },
          { name: 'prizePool', type: 'uint256' },
          { name: 'totalFunded', type: 'uint256' },
          { name: 'totalTipped', type: 'uint256' },
          { name: 'totalPaidOut', type: 'uint256' },
          { name: 'totalEntitled', type: 'uint256' },
          { name: 'submissionsClose', type: 'uint64' },
          { name: 'claimDeadline', type: 'uint64' },
          { name: 'createdAt', type: 'uint64' },
          { name: 'finalized', type: 'bool' },
          { name: 'latestVerdictHash', type: 'bytes32' },
        ],
      },
      { name: 'ids', type: 'uint256[]' },
    ],
  },
  {
    type: 'event',
    name: 'CampaignCreated',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'organizer', type: 'address', indexed: true },
      { name: 'token', type: 'address', indexed: true },
      { name: 'mode', type: 'uint8', indexed: false },
      { name: 'metadataURI', type: 'string', indexed: false },
      { name: 'submissionsClose', type: 'uint64', indexed: false },
      { name: 'claimDeadline', type: 'uint64', indexed: false },
      { name: 'seedAmount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Funded',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'from', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Tipped',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'from', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'note', type: 'string', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'WinnerSettled',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'to', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'submissionHash', type: 'bytes32', indexed: true },
      { name: 'verdictHash', type: 'bytes32', indexed: false },
      { name: 'payoutNote', type: 'string', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PrizeClaimed',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'to', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'UnclaimedReclaimed',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'winner', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'organizer', type: 'address', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TipPaid',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'to', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'submissionHash', type: 'bytes32', indexed: true },
      { name: 'verdictHash', type: 'bytes32', indexed: false },
      { name: 'payoutNote', type: 'string', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CampaignFinalized',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'refundedToOrganizer', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MetadataUpdated',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'metadataURI', type: 'string', indexed: false },
    ],
    anonymous: false,
  },
] as const;

export type TippyMakerAbi = typeof tippyMakerAbi;

export const erc20Abi = [
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'decimals',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'symbol',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'faucet',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
] as const;
